### ISSUE TITLE
Fabric-CA installation on ICP should include documentation of pre-reqs 

### ISSUE THREAD

**Issue by sachinjha** [IBM-Bluemix-Docs/blockchain#102]
1.Steps to install Fabric CA on ICP should include pre-reqs required for [PodSecurityPolicy as documented in the ibm-blockchian-platform-dev chart    ](https://github.com/IBM/charts/tree/master/stable/ibm-blockchain-platform-dev#podsecuritypolicy-requirements)
2. It should also include steps to add imagePullSecrets in the service account used for installation

**Comment by wjzhengsh** [comment]
Thanks for the comments @sachinjha !

For PodSecurityPolicy, we have provided the instruction while you installing the IBP Helm chart on ICP: https://console.bluemix.net/docs/services/blockchain/howto/helm_install_icp.html#podsecuritypolicy-requirements.

For imagePullSecrets, it is not required because we are pulling images from either **private image registry** for Enterprise Edition or **Docker hub** for Community Edition.
