### ISSUE TITLE
Unable to get system channel. Ensure MSP ID used has access to system channel and the appropriate identity is used.

### ISSUE THREAD

**Issue by nizar206** [IBM-Bluemix-Docs/blockchain#181]
when i try to add a Consortium member from the orderer i get this message "Unable to get system channel. Ensure MSP ID used has access to system channel and the appropriate identity is used." . I already repeated the network 2 times but i still get the same problem .

**Comment by pamandrejko** [comment]
@nizar206 I verified that there are no known issues around this problem.

I went through the steps in the tutorial this morning and did not encounter this problem.

Is  it  possible for you to follow along with the videos?  https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-ibp-videos#ibp-videos-ibp-v2

Otherwise, 
- Ensure you see the green status indicator on the orderer to be sure the deployment of the orderer completed successfully.
- The problem could be related to using an incorrect enroll id/secret or identity when you created your orderer node or organization.

You can also open a support ticket and the support team can help you debug the problem.

**Comment by nizar206** [comment]
@pamandrejko thank you for reply , I tried to follow the tutorial again but i still get the same problem I even tried to change my browser but no effect .
![image](https://user-images.githubusercontent.com/50301961/57572654-ef9d3e00-740c-11e9-8a81-e780ccbca011.png)

**Comment by pamandrejko** [comment]
Can you confirm your console wallet has 2 identities
<img width="814" alt="Screen Shot 2019-05-12 at 3 28 41 PM" src="https://user-images.githubusercontent.com/36892852/57586909-b3301780-74ca-11e9-9fe5-cf37261d83f8.png">
 in it?

It looks like your ordering service is missing an administrator. Here is mine (I called it orderer2, instead of orderer1)
<img width="939" alt="Screen Shot 2019-05-12 at 3 31 54 PM" src="https://user-images.githubusercontent.com/36892852/57586934-29cd1500-74cb-11e9-9045-7c17904b29ae.png">

When you create the orderer, be sure to select the correct orderer MSP and orderer Admin
<img width="553" alt="Screen Shot 2019-05-12 at 3 33 55 PM" src="https://user-images.githubusercontent.com/36892852/57586955-7b759f80-74cb-11e9-8749-6281fe819143.png">
<img width="538" alt="Screen Shot 2019-05-12 at 3 34 14 PM" src="https://user-images.githubusercontent.com/36892852/57586956-803a5380-74cb-11e9-9c62-1c8adfe9b986.png">

**Comment by nizar206** [comment]
@pamandrejko this is my wallet 
![image](https://user-images.githubusercontent.com/50301961/57664975-b8d04f00-75e9-11e9-867b-d730194d2b3d.png)

and this is my orderer
![image](https://user-images.githubusercontent.com/50301961/57665341-fe414c00-75ea-11e9-8efa-41b9055b459f.png)

 I don't why i get this problem 
![image](https://user-images.githubusercontent.com/50301961/57665415-4b252280-75eb-11e9-87ac-e475d339d77b.png)

**Comment by pamandrejko** [comment]
@nizar206 Your screenshots all look good to me. 

The only other thing I can think of is - if your service instance is older (which is fine) and it got updated with a recent beta code update, maybe it is somehow corrupted?

A more drastic measure would be to delete this service instance and create a brand new service instance to see if that helps?

It looks like you are doing everything correctly to me. So if that still fails, it would be worth considering opening a support ticket.

**Comment by pamandrejko** [comment]
@nizar206 We have GA'd our solution. I would encourage you to try again and see if you are still experiencing the same problem.

Note that you cannot migrate your existing solution to the GA release. You would need to provision a new service instance in IBM Cloud.

**Comment by joealewine** [comment]
@nizar206 The "unable to get system channel" error often occurs when the UI is not able to talk to the cluster. I would suggest refreshing your UI/cluster which you can do by clicking on the instance name in your Kubernetes dashboard, clicking "Resource List", then on the name of the service, then on "Console support", and finally on "refresh your connected cluster". 

When that process is complete, re-launch the UI using the link.

**Comment by pamandrejko** [comment]
@nizar206 The Beta trial program has now ended, so I am going to close out this issue. As I indicated above I would encourage you to try again with the GA level code here https://cloud.ibm.com/catalog/services/blockchain-platform

If you link your blockchain service instance to a free Kubernetes cluster on IBM Cloud, you will not be charged for IBM Blockchain Platform. Be aware though that a free Kubernetes cluster is automatically deleted after 30 days and your free blockchain network will no longer operate.
