### ISSUE TITLE
Blockchain Platform 2.0 console is not able to login due to Incorrect credentials

### ISSUE THREAD

**Issue by bannyle** [IBM-Bluemix-Docs/blockchain#214]
Blockchain platform 2.0 is installed on ICP 3.2, the Blockchain console is not able to login due to Incorrect credentials. 
The error message from 'couchdb' container is like this
""""""
[notice] 2019-06-24T10:00:17.841670Z nonode@nohost <0.313.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
[error] 2019-06-24T10:00:17.841712Z nonode@nohost emulator -------- Error in process <0.1975.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}
""""""
I was wondering if anyone has seen this or not, it would be appreciated if someone can help on this.

**Comment by nikhil550** [comment]
Moving to Helm charts repo.

**Comment by nikhil550** [comment]
@bannyle  This problem is a result of deploying the helm chart to a non default namespace. To deploy the helm chart to a non-default namespace, you need to apply the following security and access policies to your namespace before deploying the pod: https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-console-helm-install#console-helm-install-setup-psp. Follow the updated documentation and this problem should be resolved.
