### ISSUE TITLE
Incorrect version information in the docs

### ISSUE THREAD

**Issue by bwentwor** [IBM-Bluemix-Docs/blockchain#48]
As indicated by a customer on Stack Overflow, the Blockchain indicates a previous version of Composer. See: https://stackoverflow.com/questions/50931436/network-deployed-in-ibm-cloud-but-having-an-issue-instantiating-the-chaincode

Please update the docs.

**Comment by bwentwor** [comment]
@wjzhengsh @negupta Please update the docs.

**Comment by wjzhengsh** [comment]
@EdProsser Would you take a look?

**Comment by EdProsser** [comment]
@bwentwor @wjzhengsh What specifically needs updating? As far as I can see nothing needs updating. When they say "The blockchain indicates a previous version" that's because they were using an older incompatible version. The customer replied to their issue saying they updated to the correct composer version and everything worked. 

Please reopen this issue if anything needs changing. Thanks!
